const router = require("express").Router();
const c = require("../Controllers/roleController");
const authorize = require("../Middleware/roleMiddleware");
router.get("/permissions/all", c.permissions);
router.post("/permissions", authorize("ADMIN"), c.createPermission);
router.get("/", c.list);
router.get("/:id", c.get);
router.post("/", authorize("ADMIN"), c.create);
router.put("/:id", authorize("ADMIN"), c.update);
router.delete("/:id", authorize("ADMIN"), c.remove);
module.exports = router;
