const router = require("express").Router();
const c = require("../Controllers/salesOrderController");
router.post("/", c.create);
router.get("/", c.list);
router.get("/:id", c.get);
router.put("/:id/reserve", c.reserve);
router.put("/:id/fulfill", c.fulfill);
router.put("/:id/cancel", c.cancel);
router.post("/:id/invoice", c.invoice);
module.exports = router;
